### PR TITLE
Remove cargo clean from run and update README with volume mounting ca…

### PR DESCRIPTION
**Pull request by arlopurcell**
…rgo registry.

If you want to clean, you can always explicitly run the clean command, but I don't think there's any reason to clean on every build.

### CODE REVIEW

**Review by Ragnaroek — APPROVED** [review]

**Comment by Ragnaroek** [comment]
thanks for the PR!

**Comment by arlopurcell** [comment]
My pleasure, thanks for setting this up! Trying to get cross compiling
working on my macbook was awful

**Comment by Ragnaroek** [comment]
The change is included in the just pushed docker image 1.15.1
https://hub.docker.com/r/ragnaroek/rust-raspberry/tags/

**Comment by arlopurcell** [comment]
Awesome, thanks

**Pull request merged**
